package co.censo.vault.presentation.facetec_auth

import Processors.Config
import android.annotation.SuppressLint
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.fragment.app.FragmentActivity
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.navigation.NavController
import co.censo.vault.data.Resource
import co.censo.vault.util.vaultLog
import com.facetec.sdk.FaceTecSDK

@SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun FacetecAuthScreen(
    navController: NavController,
    viewModel: FacetecAuthViewModel = hiltViewModel()
) {

    val state = viewModel.state
    val context = LocalContext.current as FragmentActivity

    LaunchedEffect(key1 = state) {

        if (state.initFacetecData is Resource.Success) {
            Config.initializeFaceTecSDKFromAutogeneratedConfig(
                context,
                state.deviceKeyId,
                object : FaceTecSDK.InitializeCallback() {
                    override fun onCompletion(successful: Boolean) {
                        if (successful) {
                            viewModel.facetecSDKInitialized()
                        } else {
                            viewModel.failedToInitializeSDK()
                        }
                    }
                })
            viewModel.resetFacetecInitDataResource()
        }
    }

    DisposableEffect(key1 = viewModel) {
        viewModel.onStart()
        onDispose { }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                modifier = Modifier
                    .fillMaxWidth(),
                title = {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(text = "Facetec Authorization")
                    }
                })
        },
        content = {
            Box(
                Modifier
                    .fillMaxSize()
                    .background(color = Color.White),
            ) {
                Text(text = "Facetec Auth")
            }
        }
    )
}